#!/usr/bin/env php
<?php
/* (c) Anton Medvedev <anton@elfet.ru>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$loaded = false;
$deployerDir = null;
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        $loaded = true;
        $deployerDir = dirname(realpath($file)) . '/deployer/deployer';
        break;
    }
}

if (!$loaded) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}
if (is_null($deployerDir) || !file_exists($deployerDir)) {
    fwrite(STDERR,
        'Vendor "deployer/deployer" not found'
    );
    die(1);
}

// Recipe include path
set_include_path(__DIR__ . PATH_SEPARATOR . get_include_path());
set_include_path($deployerDir . PATH_SEPARATOR . get_include_path());

// Include function declarations
require_once $deployerDir . '/src/functions.php';
require_once __DIR__ . '/src/functions.php';

// Init Deployer
$console = new \Deployer\Console\Application('Deployer', 'master');
$input = new \Symfony\Component\Console\Input\ArgvInput();
$output = new \Symfony\Component\Console\Output\ConsoleOutput();
$deployer = new \Deployer\Deployer($console, $input, $output);

// Require deploy.php script
$options = getopt('f::', ['file::']);
$userSpecifiedFile = null;

if (isset($options['f'])) {
    $userSpecifiedFile = $options['f'];
} else if (isset($options['file'])) {
    $userSpecifiedFile = $options['file'];
}

if (empty($userSpecifiedFile)) {
    $deployFile = getcwd() . '/deploy.php';
} else {
    $deployFile = ($userSpecifiedFile[0] === '/' ? '' : getcwd() . '/') . $userSpecifiedFile;
}

if (is_file($deployFile) && is_readable($deployFile)) {
    require $deployFile;
}

// Run Deployer
$deployer->run();
